INSERT INTO CUSTOMER (USERNAME, EMAIL, FIRST_NAME, LAST_NAME) VALUES ('bgerard', 'test@continuum.be', 'Bart', 'Gerard');

INSERT INTO CUSTOMER_PHONE (CUSTOMER_ID, AREA_CODE, NUMBER) VALUES ('bgerard', '+32', '123456');

INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID, CITY, COUNTRY, NUMBER, STREET, ZIP_CODE, ALIAS)
VALUES ('bgerard', 'Antwerp', 'BEL', '100', 'Meir', '2000', 'home');
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID, CITY, COUNTRY, NUMBER, STREET, ZIP_CODE, ALIAS)
VALUES ('bgerard', 'Lummen', 'BEL', '7A bus 5', 'Klaverbladstraat', '3560', 'work');

INSERT INTO PRODUCT (TYPE, NAME, CATEGORY) VALUES ('CONSUMABLE', 'twix', 'CANDY');
INSERT INTO PRODUCT (TYPE, NAME, CATEGORY) VALUES ('CONSUMABLE', 'mars', 'CANDY');
INSERT INTO PRODUCT (TYPE, NAME, CATEGORY) VALUES ('CONSUMABLE', 'bounty', 'CANDY');
INSERT INTO PRODUCT (TYPE, NAME, CATEGORY) VALUES ('CONSUMABLE', 'snickers', 'CANDY');